function [Long,Lat]=xy2sky_ait(FileName,X,Y,HDUnum)
%--------------------------------------------------------------------------
% xy2sky_ait function                                             ImAstrom
% Description: Given a FITS image, SIM or a structure containing the FITS
%              WCS keyword (returned by fits_get_wcs.m), where the
%              WCS is represented using the Hammer-Aitoff
%              projection, convert X and Y position in the image to
%              longitude and latitude.
% Input  : - A string containing a FITS image name, SIM, or a structure
%            containing the FITS WCS keyword, returned by fits_get_wcs.m,
%            or a SIM structure or class.
%          - X position [pixels].
%          - Y position [pixels].
%          - HDU number in FITS image from which to read the header.
%            Default is 1.
% Output : - Longitude [radians].
%          - Latitude [radians].
% Tested : Matlab 7.13
%     By : Eran O. Ofek                    Sep 2012
%    URL : http://weizmann.ac.il/home/eofek/matlab/
% Example: [X,Y]=sky2xy_ait('File.fits',1,1);
%          % or:
%          WCS = get_fits_wcs('File.fits');
%          [X,Y]=sky2xy_ait(WCS,1,1);
%          % or:
%          Sim = images2sim('File.fits');
%          [X,Y]=sky2xy_ait(Sim,1,1);
% Reliable: 2
%--------------------------------------------------------------------------

RAD = 180./pi;

if (nargin==3),
    HDUnum = 1;
end

% deal with types of input
if (isstruct(FileName)),
    if (isfield(FileName,'CTYPE1')),
        % assume input is a WCS structure (generated by fits_get_wcs.m)
        WCS = FileName;
        CallGetWCS = false;
    else
        CallGetWCS = true;
    end
else
    CallGetWCS = true;
end

if (CallGetWCS),
    WCS = fits_get_wcs(FileName,'HDUnum',HDUnum);
end


% transformation
if (~strcmp(WCS.CUNIT1,WCS.CUNIT2)),
    error('CUNIT1 must be identical to CUNIT2');
end

switch lower(WCS.CUNIT1)
    case {'deg','degree'}
        Factor = RAD;
    case 'rad'
        Factor = 1;
    otherwise
        error('Unknown CUNIT option');
end

if (WCS.CRVAL1~=0 || WCS.CRVAL2~=0),
    error('This version does not support CRVAL ne 1');
end

X     = (X - WCS.CRPIX1).*WCS.CDELT1;
Y     = (Y - WCS.CRPIX2).*WCS.CDELT2;
[Long,Lat] = pr_ihammer_aitoff(X,Y,Factor);



